### ISSUE TITLE
ui should be a function

### ISSUE THREAD

**Issue by arashHaratian** [marlycormar/mastering_shiny_book_solutions#38]
https://github.com/marlycormar/mastering_shiny_book_solutions/blob/6c0be70c271c9778972c5b8af6244a8ca3a480a4/action-bookmark.Rmd#L20
you forgot to turn `UI` into a function:
 `ui <- function(request)`

**Comment by MayaGans** [comment]
While I don't think the UI _needs_ to be a function in order to work but I've submitted this as a PR -- thank you for your feedback!

**Comment by arashHaratian** [comment]
if you want to use **bookmarking** you definitely need to turn `ui` into a function.
